### ISSUE TITLE
登录方式改变了....

### ISSUE THREAD

**Issue by Tmn07** [qq519043202/hit-spider#2]
目前代码不能正常使用..

**Comment by Tmn07** [comment]
统一身份认证没有变化。测试网站乐学网SSL证书有问题而已:joy:

**Comment by Tmn07** [comment]
教务处登录页面改了有一段时间了。采用了RSA加密。但弱渣我还没搞定...
![image](https://cloud.githubusercontent.com/assets/12949091/25796495/462c22f6-340c-11e7-9c4f-e8dcd08e089e.png)
*****************
2017-5-8 更新说明：搞定加密了，明天去有校园网的地方试一下～

**Comment by luozifeng** [comment]
大佬 体测那个为什么会提示
Traceback (most recent call last):
  File "C:\Users\zifeng\Downloads\hit-spider-master\tice.py", line 14, in <module>
    r = s.get(baseurl, headers=headers)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='210.46.72.143', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x037D4890>: Failed to establish a new connection: [Errno 10060] ',))

**Comment by Tmn07** [comment]
回复楼上。因为体测网站关闭了

**Comment by luozifeng** [comment]
原来如此

**Comment by luozifeng** [comment]
是因为当时学校把体侧网站给关了的原因还是以后就一直不能连接了？

**Comment by Tmn07** [comment]
这个网站每年就开一会儿啊。服务器关了。等到开了才能用。
